theme: minima
title: ramblings
description: i might post math here
author: me

navbar-links:
  Math Stuff: "math"
  Physics Stuff: "physics"
  General Thoughts: "gen"
  Other Stuff: "other"
